---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags:
        - litestream_install
        - litestream_configure
        - litestream_run
  tags:
    - litestream_install
    - litestream_configure
    - litestream_run

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
      tags:
        - litestream_install
  when:
    ( not __litestream_is_installed.stat.exists ) or
      ( (__litestream_current_version_output.stderr_lines | length > 0) and
      (__litestream_current_version_output.stderr_lines[0].split("v")[1] != litestream_version) ) or
      ( (__litestream_current_version_output.stdout_lines | length > 0) and
      (__litestream_current_version_output.stdout_lines[0].split("v")[1] != litestream_version) ) or
      ( litestream_binary_local_dir | length> 0
    )
  tags:
    - litestream_install

- name: SELinux
  ansible.builtin.include_tasks:
    file: selinux.yml
    apply:
      become: true
      tags:
        - litestream_configure
  when: ansible_selinux.status == "enabled"
  tags:
    - litestream_configure

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - litestream_configure
  tags:
    - litestream_configure

- name: Ensure Litestream is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: litestream
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - litestream_run
