---
- name: Create the ceems_exporter group
  ansible.builtin.group:
    name: "{{ ceems_exporter_system_group }}"
    state: present
    system: true
  when:
    - ceems_exporter_system_group != "root"
    - ceems_exporter_create_system_user_group

- name: Create the ceems_exporter user
  ansible.builtin.user:
    name: "{{ ceems_exporter_system_user }}"
    groups: "{{ ceems_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when:
    - ceems_exporter_system_user != "root"
    - ceems_exporter_create_system_user_group

- name: Get binary
  when:
    - ceems_exporter_binary_local_dir | length == 0
    - not ceems_exporter_skip_install
  block:
    - name: Download ceems_exporter binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "{{ ceems_exporter_binary_url }}"
        dest: /tmp/ceems-{{ ceems_exporter_version }}.linux-{{ go_arch }}.tar.gz
        checksum: sha256:{{ __ceems_exporter_checksum }}
        mode: "0644"
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack ceems_exporter binary
      become: false
      ansible.builtin.unarchive:
        src: /tmp/ceems-{{ ceems_exporter_version }}.linux-{{ go_arch }}.tar.gz
        dest: /tmp
        creates: /tmp/ceems-{{ ceems_exporter_version }}.linux-{{ go_arch }}/ceems_exporter
      delegate_to: localhost
      check_mode: false

    - name: Propagate ceems_exporter binaries
      ansible.builtin.copy:
        src: /tmp/ceems-{{ ceems_exporter_version }}.linux-{{ go_arch }}/ceems_exporter
        dest: "{{ ceems_exporter_binary_install_dir }}/ceems_exporter"
        mode: "0755"
        owner: root
        group: root
      notify: restart ceems_exporter
      when: not ansible_check_mode

- name: Propagate locally distributed ceems_exporter binary
  ansible.builtin.copy:
    src: "{{ ceems_exporter_binary_local_dir }}/ceems_exporter"
    dest: "{{ ceems_exporter_binary_install_dir }}/ceems_exporter"
    mode: "0755"
    owner: root
    group: root
  when:
    - ceems_exporter_binary_local_dir | length > 0
    - not ceems_exporter_skip_install
  notify: restart ceems_exporter
