---
- name: Run target preparation
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Create sacct executable file
      ansible.builtin.copy:
        src: "files/sacct"
        dest: /usr/bin/sacct
        owner: root
        group: root
        mode: u+rx,g+rx,o+rx

    - name: Create the slurm group
      ansible.builtin.group:
        name: slurm
        state: present
        system: true

    - name: Create the slurm user
      ansible.builtin.user:
        name: slurm
        groups: slurm
        append: true
        shell: /usr/sbin/nologin
        system: true
        create_home: false
        home: /
