---
provisioner:
  inventory:
    group_vars:
      all:
        ceems_lb_web_listen_address: 127.0.0.1:9030
        ceems_lb_config:
          strategy: round-robin
          backends:
            - id: default
              tsdb_urls:
                - http://localhost:9090
