---
provisioner:
  inventory:
    group_vars:
      all:
        ceems_exporter_web_listen_address:
          - '127.0.0.1:8080'
          - '127.0.1.1:8080'

        ceems_exporter_tls_server_config:
          cert_file: /etc/ceems_exporter/tls.cert
          key_file: /etc/ceems_exporter/tls.key
        ceems_exporter_http_server_config:
          http2: true
        ceems_exporter_basic_auth_users:
          randomuser: examplepassword
        go_arch: amd64
        ceems_exporter_slurm_job_props_dir: "/run/slurmjobprops"
        ceems_exporter_gpu_job_map_dir: "/run/gpujobmap"
        ceems_exporter_ipmi_dcmi_cmd: "ipmi-dcmi"
        ceems_exporter_env_vars:
          EMAPS_API_TOKEN: foo
