---
- name: Create the dcgm_exporter group
  ansible.builtin.group:
    name: "{{ dcgm_exporter_system_group }}"
    state: present
    system: true
  when: dcgm_exporter_system_group != "root"

- name: Create the dcgm_exporter user
  ansible.builtin.user:
    name: "{{ dcgm_exporter_system_user }}"
    groups: "{{ dcgm_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: dcgm_exporter_system_user != "root"

- name: Get binary
  when:
    - dcgm_exporter_binary_local_dir | length == 0
    - not dcgm_exporter_skip_install
  tags:
    - molecule-idempotence-notest
  block:
    - name: Download golang to local folder
      become: false
      run_once: true
      ansible.builtin.get_url:
        url: "{{ _golang_download_url }}"
        dest: /tmp/golang-{{ _golang_version }}.linux-{{ go_arch }}.tar.gz
        mode: "0644"
      register: _download_golang
      until: _download_golang is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack golang
      become: false
      run_once: true
      ansible.builtin.unarchive:
        src: /tmp/golang-{{ _golang_version }}.linux-{{ go_arch }}.tar.gz
        dest: /tmp
        creates: /tmp/go
      delegate_to: localhost
      check_mode: false

    - name: Clone dcgm_exporter repository to local folder
      become: false
      run_once: true
      ansible.builtin.git:
        repo: "{{ dcgm_exporter_git_url }}"
        dest: /tmp/dcgm_exporter
        version: "{{ dcgm_exporter_version }}"
      register: _clone_repo
      delegate_to: localhost

    - name: Compile dcgm-exporter binary
      become: false
      run_once: true
      community.general.make:
        chdir: /tmp/dcgm_exporter
        target: binary
      delegate_to: localhost
      environment:
        PATH: "/tmp/go/bin:{{ ansible_env.PATH }}"
        GOPATH: "/tmp/gopath"

    - name: Propagate dcgm_exporter binaries
      ansible.builtin.copy:
        src: /tmp/dcgm_exporter/cmd/dcgm-exporter/dcgm-exporter
        dest: "{{ dcgm_exporter_binary_install_dir }}/dcgm_exporter"
        mode: "0755"
        owner: root
        group: root
      notify: restart dcgm_exporter
      when: not ansible_check_mode

- name: Propagate locally distributed dcgm_exporter binary
  ansible.builtin.copy:
    src: "{{ dcgm_exporter_binary_local_dir }}/dcgm_exporter"
    dest: "{{ dcgm_exporter_binary_install_dir }}/dcgm_exporter"
    mode: "0755"
    owner: root
    group: root
  when:
    - dcgm_exporter_binary_local_dir | length > 0
    - not dcgm_exporter_skip_install
  notify: restart dcgm_exporter
