---
- name: Restart ceems_api_server
  listen: restart ceems_api_server
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: ceems_api_server
    state: restarted
  when:
    - not ansible_check_mode
