---
provisioner:
  inventory:
    group_vars:
      all:
        ceems_api_server_web_listen_address: 127.0.0.1:8080

        ceems_api_server_tls_server_config:
          cert_file: /etc/ceems_api_server/tls.cert
          key_file: /etc/ceems_api_server/tls.key
        ceems_api_server_http_server_config:
          http2: true
        ceems_api_server_basic_auth_users:
          randomuser: examplepassword
        go_arch: amd64
        ceems_api_server_config:
          data:
            path: /var/lib/ceems
            backup_path: /tmp/ceems
          admin:
            users:
              - adm1
              - adm2
        ceems_api_server_clusters_config:
          - id: slurm-0
            manager: slurm
        ceems_api_server_updaters_config:
          - id: tsdb-0
            updater: tsdb
            extra_config:
              cutoff_duration: 5m
              queries:
                # Avgerage CPU utilisation
                avg_cpu_usage:
                  global: |
                    {% raw %}
                    avg_over_time(
                      avg by (uuid) (
                        (
                          rate(ceems_compute_unit_cpu_user_seconds_total{uuid=~"{{.UUIDs}}"}[{{.RateInterval}}])
                          +
                          rate(ceems_compute_unit_cpu_system_seconds_total{uuid=~"{{.UUIDs}}"}[{{.RateInterval}}])
                        )
                        /
                        (
                            ceems_compute_unit_cpus{uuid=~"{{.UUIDs}}"}
                          / on (instance) group_left ()
                            ceems_cpu_per_core_count
                        )
                      )[{{.Range}}:]
                    ) * 100
                    {% endraw %}
        ceems_api_server_cli_args:
          - --log.level=debug
        ceems_api_server_env_vars:
          foo: bar
