---
- name: Run local preparation
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install pyOpenSSL for certificate generation
      ansible.builtin.pip:
        name: "pyOpenSSL"

    - name: Create private key
      community.crypto.openssl_privatekey:
        path: "/tmp/tls.key"

    - name: Create CSR
      community.crypto.openssl_csr:
        path: "/tmp/tls.csr"
        privatekey_path: "/tmp/tls.key"

    - name: Create certificate
      community.crypto.x509_certificate:
        path: "/tmp/tls.cert"
        csr_path: "/tmp/tls.csr"
        privatekey_path: "/tmp/tls.key"
        provider: selfsigned

- name: Run target preparation
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Create dcgm_exporter cert dir
      ansible.builtin.file:
        path: "{{ dcgm_exporter_tls_server_config.cert_file | dirname }}"
        state: directory
        owner: root
        group: root
        mode: u+rwX,g+rwX,o=rX

    - name: Copy cert and key
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode | default('0644') }}"
      loop:
        - src: "/tmp/tls.cert"
          dest: "{{ dcgm_exporter_tls_server_config.cert_file }}"
        - src: "/tmp/tls.key"
          dest: "{{ dcgm_exporter_tls_server_config.key_file }}"
