---
galaxy_info:
  author: Mahendra Paipuri
  description: CEEMS API Server
  license: Apache
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - buster
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "37"
        - "38"
  galaxy_tags:
    - monitoring
    - prometheus
    - api
    - metrics
    - batchjob
    - hpc
    - slurm
    - cloud
    - openstack
    - k8s
    - vm
    - pod
    - cgroups
    - energy
    - gpu
