---
provisioner:
  inventory:
    group_vars:
      all:
        ceems_lb_web_listen_address: 127.0.0.1:8080
        ceems_lb_backends:
          - url: http://localhost:9090
            skip_tls_verify: true
        ceems_lb_tls_server_config:
          cert_file: /etc/ceems_lb/tls.cert
          key_file: /etc/ceems_lb/tls.key
        ceems_lb_http_server_config:
          http2: true
        ceems_lb_basic_auth_users:
          randomuser: examplepassword
        go_arch: amd64
        ceems_lb_cli_args:
          - --log.level=debug
        ceems_lb_env_vars:
          foo: bar
