---
galaxy_info:
  author: Mahendra Paipuri
  description: Litestream
  license: Apache
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - buster
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "37"
        - "38"
  galaxy_tags:
    - database
    - replication
    - sqlite
    - litestream
    - wal
    - object
    - s3
    - cloud
