---
provisioner:
  inventory:
    group_vars:
      all:
        ceems_lb_version: latest
        ceems_lb_config:
          strategy: resource-based
          backends:
            - url: http://localhost:9090
