---
provisioner:
  inventory:
    group_vars:
      all:
        ceems_lb_version: latest
        ceems_lb_config:
          strategy: round-robin
          backends:
            - id: default
              tsdb_urls:
                - http://localhost:9090
