---
name: Ansible collection publish
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: "Build the collection"
        id: build-collection
        uses: ansible-community/github-action-build-collection@main

      - name: Upload built collection to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ceems-ansible-*.tar.gz
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true

      - name: Publish collection on galaxy
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
